Add OSU Latency microbenchmarks for send/recv and isend/irecv
kokkos/kokkos-comm pull request #101
Opened 2024-06-26 16:40 UTC by nicoleavans

2024-06-26 17:12 UTC, cwpearson commented on perf_tests/test_osu_latency_sendrecv.cpp
> +    ->Range(1, 1000);
```suggestion
    ->Range(1, 1000);

```

2024-06-26 17:12 UTC, cwpearson commented
Could you please paste a snippet of example output?

2024-06-26 17:25 UTC, cwpearson requested changes

2024-06-26 17:25 UTC, cwpearson commented on perf_tests/test_osu_latency_isendirecv.cpp
> +    KokkosComm::Req recvreq = KokkosComm::irecv(v, 0, 1, comm);
If there is no  `irecv(space, ...)` overload, can you please open an issue reflecting that and pointing to this line so we can fix it? If the overload exists, let's use that instead.

2024-06-26 17:25 UTC, cwpearson commented on perf_tests/test_osu_latency_isendirecv.cpp
> +  view_type a("", state.range(0));
Give this some non-empty label.

2024-06-26 17:25 UTC, cwpearson commented on perf_tests/test_osu_latency_isendirecv.cpp
> +  view_type a("", state.range(0));
Give this some non-empty label.

2024-06-26 19:31 UTC, nicoleavans commented on perf_tests/test_osu_latency_isendirecv.cpp
> +  view_type a("", state.range(0));
https://github.com/kokkos/kokkos-comm/pull/101/commits/002a1f01ac04a4144c51cbef9b11fb314057e3bc

2024-06-26 19:31 UTC, nicoleavans commented on perf_tests/test_osu_latency_isendirecv.cpp
> +  view_type a("", state.range(0));
https://github.com/kokkos/kokkos-comm/pull/101/commits/002a1f01ac04a4144c51cbef9b11fb314057e3bc

2024-06-26 19:47 UTC, nicoleavans commented on perf_tests/test_osu_latency_isendirecv.cpp
> +    KokkosComm::Req recvreq = KokkosComm::irecv(v, 0, 1, comm);
https://github.com/kokkos/kokkos-comm/issues/102

2024-07-03 16:28 UTC, cwpearson approved these changes
Looks like we have some latency problems to fix. Thanks Nicole!

2024-07-03 16:28 UTC, merged