Update CMakeLists.txt for tests
kokkos/kokkos-comm pull request #12
Opened 2024-03-27 17:02 UTC by cedricchevalier19

- MPI is an explicit dependency for tests
- Use CMake MPI variables to launch tests

2024-03-27 17:06 UTC, masterleinad commented on perf_tests/CMakeLists.txt
> +find_package(MPI REQUIRED)  # We explicitely use MPI here
Why is this necessary? The tests are built inline and we don't try to link against an installed version here. We already find `MPI` in the main `CMakeLists.txt`.
The installation should certainly do
```
find_dependency(MPI)
```
though.

2024-03-27 19:12 UTC, cedricchevalier19 commented on perf_tests/CMakeLists.txt
> +find_package(MPI REQUIRED)  # We explicitely use MPI here
Fair point, the targets where missing the MPI::MPI_CXX, so I mechanically added this line.

```suggestion
```

2024-03-27 19:13 UTC, cedricchevalier19 commented on unit_tests/CMakeLists.txt
> +
```suggestion
```

2024-03-27 19:51 UTC, masterleinad commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
I'm even surprised that you need to link with `MPI::MPI_CXX` here explicitly. Shouldn't `KokkosComm` include this transitively?

2024-03-27 20:20 UTC, cwpearson commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
@cedricchevalier19 can you confirm that is required? I suspect that it is. If so, this is okay with me for now if we open an issue saying that the main library target should handle this transitively.

2024-04-03 10:34 UTC, cedricchevalier19 commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
It was not working on my computer, `KokkosComm` is header only so we are limited to `INTERFACE` and not `PUBLIC` so the link choice is up to the user?
 
But the real reason I have added this dependency is the source file has explicit references on MPI functions such as `MPI_Init` or `MPI_Finalize` so they must declare MPI as a **direct** dependency.

2024-04-03 12:53 UTC, masterleinad commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
Can you try again without this change? For me, only
```
target_link_libraries(test-mpi MPI::MPI_CXX)
```
ios necessary.

2024-04-03 13:11 UTC, cedricchevalier19 commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
You are right @masterleinad, it works without for `test-main`.

However I still do think that as it explicitly use `MPI` (even if through a weird header file from `impl/` directory), it should explicitly have a dependency on `MPI`.
If we provide functions like `KokkosCommInit()`, then we can avoid adding MPI.

2024-04-03 13:45 UTC, masterleinad commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
I think we should only use `target_link_libraries` when we know that the dependency doesn't come from `KokkosComm` already.

2024-04-04 14:32 UTC, cwpearson commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
> You are right @masterleinad, it works without for `test-main`.
> 
> However I still do think that as it explicitly use `MPI` (even if through a weird header file from `impl/` directory), it should explicitly have a dependency on `MPI`. If we provide functions like `KokkosCommInit()`, then we can avoid adding MPI.

As an aside that weird header file is to silence some compiler warnings we can't control from the MPI headers.

2024-04-04 15:10 UTC, cedricchevalier19 commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
I understand, sorry @cwpearson ,  my writing was quite harsh.
What I meant is if MPI header was correct enough, the dependency of the test on MPI will be clear and thus should be expressed in CMake.

2024-04-04 15:46 UTC, cwpearson commented
Maybe we should get https://github.com/cwpearson/kokkos-comm/pull/14 merged and see how it impacts this one

2024-04-04 16:09 UTC, masterleinad commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
For me, this only makes sense if there is a scenario where `KokkosComms` doesn't depend on `MPI`.

2024-04-04 17:16 UTC, cedricchevalier19 commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
I can remove the line as it is a test, but I do not think it is a good example, and I do not really the point to not add it as we directly use `MPI` functions.
It does not increase the cost of linking and will make the code less robust if we change the way that `KokkosComm` depends on `MPI`. Do I miss some hidden cost?

2024-04-04 17:17 UTC, cedricchevalier19 commented
@cwpearson, I will update it after #14 is merged.

2024-04-04 17:22 UTC, masterleinad commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
No, it's fine. It's not clear to me if there are any realistic plans to have `MPI` only as an optional dependency in the near future.

2024-04-09 10:48 UTC, cedricchevalier19 commented on perf_tests/CMakeLists.txt
> +target_link_libraries(perf_test-main KokkosComm benchmark::benchmark MPI::MPI_CXX)
In a near future I do not see MPI becoming optional.

2024-04-09 12:11 UTC, dalg24 commented on perf_tests/CMakeLists.txt
> +find_package(MPI REQUIRED)
Don;t you get it transitively since KokkosComm will do find_dependency(MPI) ?

2024-04-09 12:26 UTC, cedricchevalier19 commented on perf_tests/CMakeLists.txt
> +find_package(MPI REQUIRED)
For now, yes, but I do not think it is very robust.
For example, for the in source build, if we move `find_package(MPI)` in the src directory instead of the root, `MPIEXEC_*` variables will not be visible anymore.

Ideally, I would have had also explicit dependency on Kokkos, but it is true that I am not used to header-only libraries.

2024-04-10 16:38 UTC, cedricchevalier19 commented
Waiting for #26

2024-04-11 21:45 UTC, cwpearson requested changes

2024-04-11 21:45 UTC, cwpearson commented on perf_tests/CMakeLists.txt
> +find_package(MPI REQUIRED)
Let's defer this change until it's actually a problem

2024-04-11 21:45 UTC, cwpearson commented on unit_tests/CMakeLists.txt
> +find_package(MPI REQUIRED)
Same as perf_tests

2024-04-11 21:45 UTC, cwpearson commented on .editorconfig
An attempt to impose formatting suggestions for cmake and markdown files?

2024-04-11 21:45 UTC, cwpearson commented on cmake/KokkosComm_configuration.hpp.in
Expectation is that future configure-time info will go in here? (definitions, etc?)

2024-04-12 09:05 UTC, cedricchevalier19 commented on cmake/KokkosComm_configuration.hpp.in
Yes, It was to deal with `MDSpan` stuff but I think it might still be useful. I can revert to `version` if you really want to.

2024-04-12 09:06 UTC, cedricchevalier19 commented on unit_tests/CMakeLists.txt
> +find_package(MPI REQUIRED)
Will do but I truly think it is a bad idea.

2024-04-12 09:09 UTC, cedricchevalier19 commented on .editorconfig
CMake were not uniformly formatted. I do not care about styling but I wish our files were coherent.
I put it in this PR as it was also a CMake related one.

2024-04-12 22:04 UTC, cwpearson commented on cmake/KokkosComm_configuration.hpp.in
This will be useful in the future!

2024-04-12 22:07 UTC, cwpearson submitted a review, later dismissed

2024-04-13 00:08 UTC, dalg24 commented on .editorconfig
What is that file?
How does it belong to this PR?

2024-04-13 00:11 UTC, dalg24 commented on cmake/flags.cmake
> +check_and_add_flag(KokkosCommFlags -Wno-gnu-zero-variadic-macro-arguments)
Why would we add any of these flags to the target?!

2024-04-13 00:12 UTC, dalg24 commented on cmake/flags.cmake
> +check_and_add_flag(KokkosCommFlags -pedantic)
Aren't these two just aliases for the same thing?

2024-04-15 08:16 UTC, cedricchevalier19 commented on .editorconfig
It is a small guess for uniformly formatting CMake files, that's the reason it is in the PR.

2024-04-15 08:21 UTC, cedricchevalier19 commented on cmake/flags.cmake
> +check_and_add_flag(KokkosCommFlags -Wno-gnu-zero-variadic-macro-arguments)
I kept the previous behavior. Currently it is flagged on the `BUILD`.

2024-04-15 12:24 UTC, dalg24 commented on .editorconfig
Why don't use a source code formatter instead?

2024-04-15 12:25 UTC, dalg24 commented on cmake/flags.cmake
> +check_and_add_flag(KokkosCommFlags -Wno-gnu-zero-variadic-macro-arguments)
That's fair

2024-04-15 13:35 UTC, masterleinad commented on .editorconfig
The danger with such a file if not enforced is that we might end up with a good number of unrelated formatting changes depending on who works on a pull request.

2024-04-17 18:44 UTC, cedricchevalier19 commented on .editorconfig
I have removed the file. Will look at a better solution later.

2024-04-17 18:45 UTC, cedricchevalier19 commented on cmake/flags.cmake
> +check_and_add_flag(KokkosCommFlags -pedantic)
Perhaps, but I am pretty sure we can find a compiler that deals with them differently.

2024-05-14 17:33 UTC, cwpearson requested changes

2024-05-14 17:33 UTC, cwpearson commented on unit_tests/CMakeLists.txt
> +
Delete these comments

2024-05-14 17:33 UTC, cwpearson commented on perf_tests/CMakeLists.txt
> +
Remove comments

2024-05-15 09:59 UTC, cedricchevalier19 commented on unit_tests/CMakeLists.txt
> +
If the comments are the ones of the following lines, sorry but I do not agree.
(please consider that I am not a native English speaker).

To me, not using `find_package(MPI)` is already wrong practice as we should explicitly require what we are directly using. Relying on transitive dependencies is evil (I've spent my share of time dealing with this nightmare when updating software packages at Spack level). Most of the time `tests` are also `examples` for end-user, so I want to give them a correct template.
Despite this, for these tests, I have agreed to not do `find_package(MPI)` in order to test that the `find_dependency(MPI)` is correctly set.

By the way, I should have added `find_package(Kokkos)`too.

If test code does not reference anymore any `MPI` functions directly, then I'll happily remove everything.

2024-05-15 09:59 UTC, cedricchevalier19 commented
Have to rebase this branch.

2024-05-15 18:24 UTC, cwpearson commented on unit_tests/CMakeLists.txt
> +
How would you feel about adding a comment to the top of the file saying something like "These tests require Kokkos and MPI, but we're not using find_package(...) here because we want to make sure KokkosComm's find_dependency is working"?

2024-09-17 08:22 UTC, cedricchevalier19 commented
Superseded by #122 .

2024-09-17 08:22 UTC, closed without merging