Feature: Add basic NCCL communication space backend
kokkos/kokkos-comm pull request #128
Opened 2024-11-14 18:46 UTC by dssgabriel

This is still very much WIP and cannot build at the moment. I am simply opening the PR so that folks meeting at SC24 can exchange on it. :+1:

2024-12-16 16:23 UTC, cedricchevalier19 reviewed
Some thoughts.

2024-12-16 16:23 UTC, cedricchevalier19 commented on src/KokkosComm/fwd.hpp
> +class Mpi;
I think I should depend on MPI in this case.

2024-12-16 16:23 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/req.hpp
> +  return false;
Should you block one request if none of the input is ready?

2024-12-16 16:23 UTC, cedricchevalier19 commented on src/KokkosComm/collective.hpp
> +  return Impl::Reduce<SendView, RecvView, RedOp, ExecSpace, CommSpace>(h, sv, rv, root);
I do not exactly understand how it will work. Don't we need to call it `execute()`?

2024-12-16 16:23 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/reduce.hpp
> +      space.fence();  // is this fence necessary?
I would remove this fence.

2024-12-16 16:23 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/reduce.hpp
> +      space.fence();  // is this fence necessary?
Not needed in my opinion.

2024-12-16 16:23 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/impl/packer.hpp
> +struct NcclArgs {
I think `PackedViewNccl` or something like that will be a better name. Looking at the following code, I thought `NCClArgs` was an NCCL thing.

2024-12-16 17:18 UTC, dssgabriel commented on src/KokkosComm/collective.hpp
> +  return Impl::Reduce<SendView, RecvView, RedOp, ExecSpace, CommSpace>(h, sv, rv, root);
You are right, I fixed this in [`9c185af` (#128)](https://github.com/kokkos/kokkos-comm/pull/128/commits/9c185af34dd8b449d414e72bacdf0602bb8c5a37).

2024-12-18 22:56 UTC, cwpearson commented
I think it builds now. My workstation has GPU-aware MPI problems, so I need to fix those before continuing.

2025-07-04 14:22 UTC, dssgabriel commented
Just rebased this on top of latest `develop`.

2025-07-04 20:39 UTC, dssgabriel commented on src/KokkosComm/fwd.hpp
> +class Mpi;
Fixed in https://github.com/kokkos/kokkos-comm/pull/128/commits/68a7609dd1dea37e5d7eeeaceceb9e62f2bc0fe0 :+1:

2025-07-04 20:40 UTC, dssgabriel commented on src/KokkosComm/nccl/req.hpp
> +  return false;
At least for now, I am following what we do for MPI.

2025-07-04 20:40 UTC, dssgabriel commented on src/KokkosComm/nccl/impl/packer.hpp
> +struct NcclArgs {
Fixed in https://github.com/kokkos/kokkos-comm/pull/128/commits/926438ff81b9d4310e8a279d25dceb6def5be6f4 :+1:

2025-07-04 20:46 UTC, dssgabriel commented
@cwpearson Looks like https://github.com/kokkos/kokkos-comm/pull/128/commits/f25f24359bd4fe82c20980f59cb3bafe4ce0e390 breaks a lot of stuff.

Should we prefer KokkosComm custom "marker" structs for our reduction operators instead of trying to use Kokkos Core's built-in reducers?
This is what I initially did, but after a discussion with @cedricchevalier19  (albeit a few months ago), I thought we could use the ones provided by Core instead, but that doesn't seem to work. Compilation crashes as these expect some template parameters, which isn't practical for our users and is unrelated to an MPI/NCCL reduction comm, IMHO.

I reverted in https://github.com/kokkos/kokkos-comm/pull/128/commits/887b606603a31996812115fb8fc1e6f312731091. Tell me if you think it's better to go with Kokkos Core's built-in reducers as "markers".

2025-07-04 21:09 UTC, dssgabriel commented
Everything builds after the big refactor! :partying_face: 

The only missing things before merging this should be:
- [ ] update the CI to enable building the full NCCL backend
- [ ] add some more NCCL tests (which should be run in CI?)

2025-07-18 21:44 UTC, cwpearson requested changes
Generally it looks okay, thanks for the hard work!

2025-07-18 21:44 UTC, cwpearson commented on CMakeLists.txt
What's with the (seemingly?) spurious removals in this file?

2025-07-19 15:40 UTC, dssgabriel commented on CMakeLists.txt
That is weird. I haven't touch at the top-level CMake since opening the PR so I must have messed something up when rebasing. Will fix!

2025-07-19 15:47 UTC, dssgabriel commented on CMakeLists.txt
Reverted in #429c3b0.

2025-07-19 17:00 UTC, dssgabriel commented
Do we want to write the tests and enable the CI for NCCL in this PR or should we break this up into smaller ones?

2025-07-21 14:34 UTC, cwpearson commented
> Do we want to write the tests and enable the CI for NCCL in this PR or should we break this up into smaller ones?

If we could have at least one test (even a minimal one) that would be great. Would it be easiest to add a build-only test running under GitHub actions? It would also serve as a minimal example of how to use the API.

Then we can add additional real tests running at SNL or CEA.

2025-07-28 08:17 UTC, cedricchevalier19 commented
I think only a build test is enough for now.

2025-07-28 08:26 UTC, cedricchevalier19 reviewed
If it is not too hard, set up a build test on GitHub. Else, if it is a significant amount of work,  I am OK to merge it as-is and add the CI in another PR.

2025-07-28 08:26 UTC, cedricchevalier19 commented on unit_tests/nccl/test_nccl.cpp
> +
Add a comment that this test is a NCCL smoke test, nothing related to Kokkos-Comm.

2025-07-28 08:26 UTC, cedricchevalier19 commented on unit_tests/CMakeLists.txt
> +  # doesn't use KokkosComm, so explicitly link MPI
```suggestion
  # doesn't use KokkosComm, so explicitly link with NCCL
```

2025-07-28 08:26 UTC, cedricchevalier19 commented on cmake/FindNCCL.cmake
> +  mark_as_advanced(NCCL_ROOT_DIR NCCL_INCLUDE_DIRS NCCL_LIBRARIES)
We should define proper CMake targets instead of relying on variable. (Not mandatory in this PR, can be improved later).

2025-07-29 14:50 UTC, cwpearson commented
> @cwpearson Looks like [f25f243](https://github.com/kokkos/kokkos-comm/commit/f25f24359bd4fe82c20980f59cb3bafe4ce0e390) breaks a lot of stuff.
> 
> Should we prefer KokkosComm custom "marker" structs for our reduction operators instead of trying to use Kokkos Core's built-in reducers? This is what I initially did, but after a discussion with @cedricchevalier19 (albeit a few months ago), I thought we could use the ones provided by Core instead, but that doesn't seem to work. Compilation crashes as these expect some template parameters, which isn't practical for our users and is unrelated to an MPI/NCCL reduction comm, IMHO.
> 
> I reverted in [887b606](https://github.com/kokkos/kokkos-comm/commit/887b606603a31996812115fb8fc1e6f312731091). Tell me if you think it's better to go with Kokkos Core's built-in reducers as "markers".

In today's meeting, we agreed it's fine to move forward with Kokkos Comm tag structs rather than trying to use Kokkos Core ones

2025-09-18 17:41 UTC, cwpearson requested changes
Generally looks great, thanks for the hard work. It's a bit tough to review such a big PR, but with these things fixed I will be fine merging it and resolving any issues as they arise.

2025-09-18 17:41 UTC, cwpearson commented on cmake/FindNCCL.cmake
I think we're obliged to respect the pytorch license
* put FindNCCL in its own subdirectory (maybe `cmake/thirdparty/pytorch/...`)
* Copy the Pytorch License into that subdirectory as well - the pytorch license allows reusing and redistributing their code.
* Modify our cmake so it can still find the file in this new location

2025-09-18 17:41 UTC, cwpearson commented on unit_tests/CMakeLists.txt
Some of these cmake diffs will probably go away with the new cmake formatting?

2025-09-18 18:12 UTC, dssgabriel commented on unit_tests/CMakeLists.txt
Yes, I will rebase on top of `develop` and hopefully these should disappear.

2025-09-18 20:38 UTC, dssgabriel commented on cmake/FindNCCL.cmake
Resolved in a74c96da530c1e64b5a65ce2828eeefe3bf5f0a6

2025-09-18 20:44 UTC, dssgabriel commented
We still need a compile-only CI workflow before merging, though. Maybe we can simply fetch an MPI binary instead of recompiling our own for the KokkosComm+NCCL build (unlike we do for the MPI workflow).
Ideally, I would like to add unit tests for the collectives as well, so that we have full coverage on the build pipeline.

Hopefully, I will have this ready before Tuesday's meeting next week, so we can discuss it with everyone and decide whether it's best to split it into smaller PRs so multiple people can easily review.
E.g., we could split it as:
1. NCCL infra: CMake stuff, compile-options, CI workflows, test utils, etc. (could be further split up if we want to)
2. Structure specializations
3. P2P interfaces + unit tests
4. Collectives interfaces + unit tests

2025-09-19 14:49 UTC, cwpearson commented
Maybe it's easiest to define a simple docker container? e.g. maybe Nvidia provides a base image, then we install nccl and MPI, then run the CI inside the container.

2025-09-19 16:36 UTC, dssgabriel commented
> Maybe it's easiest to define a simple docker container? e.g. maybe Nvidia provides a base image, then we install nccl and MPI, then run the CI inside the container.

Yes, this seems to be the way to go.
I am trying to build both MPICH and OpenMPI with CUDA support using a base image from NVIDIA, and generate custom container images that we cache (this ties in with #86). Then, we do build-only jobs of Kokkos-master + KokkosComm_MPI/KokkosComm_NCCL with each MPI implementation. This should significantly speed up the build-only CI and let us test both major MPI vendors in one shot.

The only thing I am wondering is, should we actually build MPIs, or can we directly install binaries that are CUDA-aware? If we do build, do we do it as part of the Linux Compile-Only workflow or separate it? All of this should be in its own PR, though.

2025-09-19 16:53 UTC, cwpearson commented
if we can get a CUDA-aware binary install that's completely fine.

2025-09-23 22:20 UTC, dssgabriel commented
Some updates on this PR:

1. I have reworked the `FindNCCL.cmake` module following [CMake's documentation](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules), so we now roll our own instead of using PyTorch's one.
   
   Also, we now expose targets so we can idiomatically link against NCCL with:
   ```cmake
   target_link_libraries(KokkosComm INTERFACE NCCL::NCCL)
   ```

2. I have enabled building KokkosComm with the NCCL backend in the Compile-only workflow, but I still need to update this to run concurrently with the build of KComm on the MPI backend. 
   
   Apart from [this NVHPC image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/nvhpc?version=25.7-devel-cuda12.9-ubuntu24.04), I could not find pre-built binaries of an MPI impl with CUDA support. I see two options:
   - We use the NVHPC image directly (though I think it's much bigger than the CUDA one we currently use), or;
   - We cache the CUDA-aware Open MPI build and reuse it in this workflow (see #86).
  
   What do you think @cwpearson @cedricchevalier19 ?
  
3. Now that the CI attempts to build the NCCL backend, it looks like I will have a few issues to fix, so I'll be working on that (probably only on the evenings and weekend though, since I have higher priority PhD stuff on the table).

Once everything passes the CI checks, I think we should work on splitting this PR up into reviewable chunks.

2025-10-13 10:21 UTC, dssgabriel commented
At last, the compile-only workflow finally passes with the NCCL backend! :tada: 

I will add the remaining tests for the NCCL collectives, and this should be ready to merge.

2025-10-14 15:50 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/recv.hpp
> +    space.fence();  // make sure allocation is complete before receiving
I do not think this `fence()` is necessary as `pack()` seems to follow the logic of Kokkos to enqueue its work in the space.

2025-10-14 15:50 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/recv.hpp
> +    auto args    = Packer::pack(space, rv);
`Packer::allocate_packed_for` looks more appropriate. We do not need to copy the original view in the reception buffer.

2025-10-14 15:50 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/reduce.hpp
> +      space.fence();
```suggestion
```

I think we do not need to `fence()`.

2025-10-14 15:50 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/reduce.hpp
> +    space.fence();
```suggestion
```

2025-10-14 15:50 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/reduce.hpp
> +      space.fence();
```suggestion
```

2025-10-14 15:50 UTC, cedricchevalier19 commented on src/KokkosComm/nccl/send.hpp
> +    space.fence();  // make sure packing is complete before sending
```suggestion
```

2025-10-23 21:29 UTC, cwpearson approved these changes

2025-10-23 21:29 UTC, merged