Get `cmake --build --target install` working
kokkos/kokkos-comm pull request #14
Opened 2024-03-28 16:58 UTC by cwpearson

* Make install work
* Add a CI check that builds unit tests and perf tests against the install
* Add a CMake configuration `-DKokkosComm_INSTALL_TESTING=ON` that uses `find_package` to find KokkosComm and then builds unit tests and perf tests against that
* There are probably many problems with this that I don't know enough about CMake to forsee

2024-04-03 17:23 UTC, cedricchevalier19 requested changes
It's a great idea, but it can be implemented in a simpler manner I think.

You can make the tests an independent project that contains a

```cmake
if (NOT TARGET KokkosComm::KokkosComm)
  find_package(KokkosComm REQUIRED)
endif()
```

This way, we do not need special option and we keep the main CMakeLists.txt clean.

2024-04-03 17:23 UTC, cedricchevalier19 commented on .github/workflows/linux-install.yaml
> +          cd "$KOKKOS_SRC" && git checkout 4.2.00
```suggestion
mkdir "$KOKKOS_SRC" && curl -sfL https://github.com/kokkos/kokkos/archive/refs/tags/4.2.01.tar.gz | tar xvz - --strip-components=1 -C "$KOKKOS_SRC"
```

Else we can clone only the last commit of the given tag.

2024-04-03 17:23 UTC, cedricchevalier19 commented on .github/workflows/linux-install.yaml
> +          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON -DC
```suggestion
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DCMAKE_CXX_COMPILER=mpicxx
```

We do not know if GitHub actions run on homogeneous machines, so do not over-optimize for CI-robustness.
Do we really need both `SERIAL` and `OPENMP`?

2024-04-03 17:23 UTC, cedricchevalier19 commented on CMakeLists.txt
> +option(KokkosComm_INSTALL_TESTING "Build unit tests against an installed KokkosComm" OFF)
I do not think it is a good idea to have this option globally.

2024-04-03 17:23 UTC, cedricchevalier19 commented on CMakeLists.txt
> +set(KOKKOSCOMM_INSTALL_TESTING ${KokkosComm_INSTALL_TESTING} CACHE BOOL "" FORCE)
Is there any reason to double the options with cache variables?
It is not introduced by this commit but I was wondering if we can get rid of this double layers of variables.

2024-04-03 17:23 UTC, cedricchevalier19 commented on cmake/Config.cmake.in
> +## FIXME: do we need this?
If we use targets, we do not need the later.

2024-04-03 17:23 UTC, cedricchevalier19 commented on src/CMakeLists.txt
> +add_library(KokkosComm::KokkosComm ALIAS KokkosComm)
Great!

2024-04-03 17:23 UTC, cedricchevalier19 commented on src/KokkosComm.hpp
> +#include "KokkosComm_concepts.hpp"
I think it is not a good idea to rely on include paths as we know we want to use our files.

2024-04-03 17:36 UTC, cedricchevalier19 commented on cmake/Config.cmake.in
> +## FIXME: do we need this?
However, we should have
```cmake
include(CMakeFindDependencyMacro)
find_dependency(MPI)
```

2024-04-04 14:39 UTC, cwpearson commented on .github/workflows/linux-install.yaml
> +          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON -DC
Just making sure things work when two backends are enabled. Could be OpenMP or Threads.

2024-04-04 14:39 UTC, cwpearson commented on .github/workflows/linux-install.yaml
> +          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON -DC
I'm okay with removing Kokkos_ARCH_NATIVE

2024-04-04 15:14 UTC, cedricchevalier19 commented on cmake/Config.cmake.in
> +## FIXME: do we need this?
We should also add `find_dependency(Kokkos)`.

2024-04-04 15:37 UTC, cwpearson commented on .github/workflows/linux-install.yaml
> +          cd "$KOKKOS_SRC" && git checkout 4.2.00
I switched this to a shallow clone of the tag with `git clone --branch <tag> --depth 1` (the `--branch` flag is a bit misleading but it can accept a tag)

2024-04-04 15:39 UTC, cwpearson commented on CMakeLists.txt
> +set(KOKKOSCOMM_INSTALL_TESTING ${KokkosComm_INSTALL_TESTING} CACHE BOOL "" FORCE)
This is what Core does and I'm not knowledgeable enough about CMake to explain why (or more importantly, why not).

2024-04-04 15:40 UTC, cwpearson commented on src/KokkosComm.hpp
> +#include "KokkosComm_concepts.hpp"
Would it be okay to follow along with Core and install the `impl` dir, rather than what we're doing right now which is flattening `impl` into the installation include directory?

2024-04-04 15:41 UTC, cwpearson commented on src/KokkosComm.hpp
> +#include "KokkosComm_concepts.hpp"
Either way let's worry about this in another PR

2024-04-04 16:06 UTC, masterleinad commented on .github/workflows/linux-install.yaml
> +   Kokkos-040201-OpenMPI:
You could just test with `Kokkos` `master`.

2024-04-04 16:06 UTC, masterleinad commented on .github/workflows/linux-install.yaml
> +          ls ${{ github.workspace }}
```suggestion
        run: ls ${{ github.workspace }}
```

2024-04-04 16:06 UTC, masterleinad commented on .github/workflows/linux-install.yaml
> +          git clone https://github.com/kokkos/kokkos.git --branch 4.2.01 --depth 1 "$KOKKOS_SRC"
```suggestion
          git clone https://github.com/kokkos/kokkos.git --branch master --depth 1 "$KOKKOS_SRC"
```

2024-04-04 16:06 UTC, masterleinad commented on .github/workflows/linux-install.yaml
> +          cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wshadow
Why are you specifying extra flags here? Aren't they already set in `cmake/flags.cmake`?
```suggestion
          cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkosComm_ENABLE_TESTS=OFF -DKokkosComm_ENABLE_PERFTESTS=OFF -DCMAKE_INSTALL_PREFIX="$COMM_INSTALL"
```

2024-04-04 16:06 UTC, masterleinad commented on CMakeLists.txt
> +
```suggestion
```

2024-04-04 16:06 UTC, masterleinad commented on CMakeLists.txt
> +    RUNTIME DESTINATION bin
What are we installing in `bin`?

2024-04-04 16:06 UTC, masterleinad commented on CMakeLists.txt
> +    # enable_testing()
Why does this need to be a `CACHE` variable? Why is `enable_testing` commented?

2024-04-04 16:06 UTC, masterleinad commented on cmake/Config.cmake.in
> +## FIXME: do we need this?
How are the following `CMake` variables used?

2024-04-04 16:06 UTC, masterleinad commented on docs/dev/testing.rst
> +2. Do another build with the ``unit_tests`` directory as the source. You will need to provide ``-DKokkosComm_DIR=/path/to/KokkosComm/install/lib/cmake/KokkosComm`` just as any other external project
```suggestion
2. Do another build with the ``unit_tests`` directory as the source. You will need to provide ``-DKokkosComm_ROOT=/path/to/KokkosCommInstallation`` just as any other external project would
```

2024-04-04 16:06 UTC, masterleinad commented on docs/dev/testing.rst
> +    cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wshadow -Wped
Again, why are you setting warning flags explicitly if this is already done in your `kokkoscomm_add_cxx_flags` macro?

2024-04-04 16:06 UTC, masterleinad commented on docs/dev/testing.rst
> +    cmake -S "$COMM_SRC"/unit_tests -B "$COMM_UNIT_TESTS_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DKokkosComm_DIR="$COMM_INSTALL"/lib/cmake/KokkosComm -DCMAKE_CXX_COMPILER=mpicxx -DCMA
Why don't you set `CMAKE_CXX_FLAGS` here?

2024-04-04 16:06 UTC, masterleinad commented on docs/usage/getting_started.rst
> +      -DKokkos_DIR=/path/to/kokkos/install/lib/cmake/Kokkos
or
```suggestion
      -DKokkos_ROOT=/path/to/kokkos-install/
```

2024-04-04 16:06 UTC, masterleinad commented on perf_tests/CMakeLists.txt
> +if(KOKKOSCOMM_TESTS_ARE_SUBDIRECTORY)
```suggestion 
get_directory_property(hasParent PARENT_DIRECTORY)
if(hasParent)
```
or just
```suggestion
if(KOKKOSCOMM_ENABLE_TESTS)
```
or again
```suggestion
if (NOT TARGET KokkosComm::KokkosComm)
```
?

2024-04-04 17:04 UTC, cedricchevalier19 requested changes
I am a little skeptical about using `mpicxx` as a compiler. 
`MPI` does not require it and it can make things strange mixing with `gpu` compilers.

However, this change can be done in a separate PR if you prefer to ensure all part of the repository are updated.

2024-04-04 17:04 UTC, cedricchevalier19 commented on .github/workflows/linux-install.yaml
> +          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DCMAKE_CXX_COMPILER
```suggestion
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON
```

It is not a good idea to use `mpicxx`. `CMake` should interrogate the wrapper to push the correct `MPI` flags, if needed.

2024-04-04 17:04 UTC, cedricchevalier19 commented on .github/workflows/linux-install.yaml
> +          cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkosComm_ENABLE_TESTS=OFF -DKokkosCom
```suggestion
          cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkosComm_ENABLE_TESTS=OFF -DKokkosComm_ENABLE_PERFTESTS=OFF -DCMAKE_INSTALL_PREFIX="$COMM_INSTALL"
```

By using `mpicxx`, we miss undeclared dependency on `MPI` for `test-mpi`. `CMake` should find correct `MPI` flags if `mpirun` is in the path.

2024-04-04 17:04 UTC, cedricchevalier19 commented on .github/workflows/linux-install.yaml
> +          cmake -S "$COMM_SRC"/unit_tests -B "$COMM_UNIT_TESTS_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DKokkosComm_ROOT="$COMM_INSTALL" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=
```suggestion
          cmake -S "$COMM_SRC"/unit_tests -B "$COMM_UNIT_TESTS_BUILD" -DKokkos_ROOT="$KOKKOS_INSTALL" -DKokkosComm_ROOT="$COMM_INSTALL"  -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

2024-04-04 17:04 UTC, cedricchevalier19 commented on .github/workflows/linux-install.yaml
> +          cmake -S "$COMM_SRC"/perf_tests -B "$COMM_PERF_TESTS_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DKokkosComm_ROOT="$COMM_INSTALL" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=
```suggestion
          cmake -S "$COMM_SRC"/perf_tests -B "$COMM_PERF_TESTS_BUILD" -DKokkos_ROOT="$KOKKOS_INSTALL" -DKokkosComm_ROOT="$COMM_INSTALL" -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

2024-04-04 17:04 UTC, cedricchevalier19 commented on CMakeLists.txt
> +    $<INSTALL_INTERFACE:include>
```suggestion
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
```

And move up `include(GNUInstallDirs)`

2024-04-04 17:04 UTC, cedricchevalier19 commented on CMakeLists.txt
> +    RUNTIME DESTINATION bin
And why not using `${CMAKE_INSTALL_BINDIR}`?

2024-04-04 17:04 UTC, cedricchevalier19 commented on docs/dev/testing.rst
> +    cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkosComm_ENABLE_TESTS=OFF -DKokkosComm_ENAB
```suggestion
    cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DKokkos_ROOT="$KOKKOS_INSTALL"  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkosComm_ENABLE_TESTS=OFF -DKokkosComm_ENABLE_PERFTESTS=OFF -DCMAKE_INSTALL_PREFIX="$COMM_INSTALL"
```

2024-04-04 17:04 UTC, cedricchevalier19 commented on docs/dev/testing.rst
> +    cmake -S "$COMM_SRC"/unit_tests -B "$COMM_UNIT_TESTS_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DKokkosComm_ROOT="$COMM_INSTALL" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=RelWit
```suggestion
    cmake -S "$COMM_SRC"/unit_tests -B "$COMM_UNIT_TESTS_BUILD" -DKokkos_ROOT="$KOKKOS_INSTALL" -DKokkosComm_ROOT="$COMM_INSTALL" -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

2024-04-04 17:04 UTC, cedricchevalier19 commented on docs/dev/testing.rst
> +    cmake -S "$COMM_SRC"/perf_tests -B "$COMM_PERF_TESTS_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DKokkosComm_ROOT="$COMM_INSTALL" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=RelWit
```suggestion
    cmake -S "$COMM_SRC"/perf_tests -B "$COMM_PERF_TESTS_BUILD" -DKokkos_ROOT="$KOKKOS_INSTALL" -DKokkosComm_ROOT="$COMM_INSTALL" -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

2024-04-04 17:04 UTC, cedricchevalier19 commented on docs/dev/testing.rst
> +.. code-block:: bash
We could almost run this script in the CI! It will ensure that it is correct and up-to-date.

2024-04-04 17:04 UTC, cedricchevalier19 commented on unit_tests/CMakeLists.txt
>  add_executable(test-mpi test_mpi.cpp)
`test_mpi` should have an explicit dependency on `MPI`. Visible by not using `mpicxx` as a compiler.

2024-04-04 17:36 UTC, cwpearson commented
> I am a little skeptical about using `mpicxx` as a compiler. `MPI` does not require it and it can make things strange mixing with `gpu` compilers.
> 
> However, this change can be done in a separate PR if you prefer to ensure all part of the repository are updated.

I agree, let's tackle this in another PR. I created an issue: https://github.com/cwpearson/kokkos-comm/issues/17

2024-04-04 17:38 UTC, cwpearson commented on unit_tests/CMakeLists.txt
>  add_executable(test-mpi test_mpi.cpp)
Let's fix this as part of https://github.com/cwpearson/kokkos-comm/issues/17

2024-04-04 17:52 UTC, cwpearson commented on docs/dev/testing.rst
> +    cmake -S "$COMM_SRC"/unit_tests -B "$COMM_UNIT_TESTS_BUILD" -DKokkos_DIR="$KOKKOS_INSTALL/lib/cmake/Kokkos" -DKokkosComm_DIR="$COMM_INSTALL"/lib/cmake/KokkosComm -DCMAKE_CXX_COMPILER=mpicxx -DCMA
I think we're consistent about not setting in anywhere in the files this PR touches now :D

2024-04-04 17:55 UTC, cwpearson commented on CMakeLists.txt
> +    RUNTIME DESTINATION bin
Nothing in `bin`. Just an oversight while learning how CMake install works. Will remove.

2024-04-04 17:57 UTC, cwpearson commented on .github/workflows/linux-install.yaml
> +          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DCMAKE_CXX_COMPILER
Will address in a resolution to https://github.com/cwpearson/kokkos-comm/issues/17

2024-04-04 18:29 UTC, cedricchevalier19 approved these changes

2024-04-05 15:01 UTC, merged