zero overhead low level api
kokkos/kokkos-comm pull request #50
Opened 2024-05-08 19:11 UTC by dutkalex

This PR proposes a design which we've had some success with in our in-house solution. This does not have to be integrated as is, the goal is rather to initiate a discussion on the design aspects. I believe this design enables to support the current type-erased solution implemented in the `Req` class, but is also compatible with other semantics/tradeoffs

2024-05-09 13:58 UTC, devreal commented on src/KokkosComm_communicator.hpp
> +          MPI_Send( send_view.data(), send_view.size(), mpi_type<T>(), dest_rank, tag, _raw_comm );
Shouldn't they map to the existing kokkos com send templates to get proper datatype handling / packing?

2024-05-09 14:02 UTC, dutkalex commented on src/KokkosComm_communicator.hpp
> +          MPI_Send( send_view.data(), send_view.size(), mpi_type<T>(), dest_rank, tag, _raw_comm );
Yes, I agree. I am currently experimenting a few design ideas (hence the all in one file thing), but of course the goal is not to have duplicate code in the end.

2024-05-09 21:12 UTC, dutkalex commented
Different problems requires different communication strategies. Therefore, using `KokkosComm` should not force the user to use a suboptimal communication mechanism with regards to his problem domain. This PR proposes a first draft of a flexible enough design (IMO at least, please let me know if I'm missing something), which decouples the wrapping of the raw MPI functionalities from the higher-level communication scheme. I have laid out the outline of 2 very different schemes both relying on the same low level wrappers to demonstrate my point: the current type-erased solution, and a more static solution (roughly mirroring what I have developed for our in-house CFD solver) which is better suited for reccurent communication patterns which are known ahead of time

2024-05-10 14:05 UTC, devreal commented
In general: what is the benefit of having two ways of doing the same thing? There are free-standing functions and this introduces member functions that (ideally) do the same. Can you explain a little more what the upside of member functions is?

2024-05-10 14:58 UTC, dutkalex commented
What I advocate for is not having two ways of doing the same thing. 

The first idea I advocate for is to decouple the wrapping of the raw MPI primitives from the communication scheme considerations. The current implementation forces the user to either use the type-erased solution which is not the best solution for all problems. Therefore, I think it makes sense to first introduce basic idiomatic C++ wrappers to ease manipulation of the raw MPI primitives, and then built on top of that to propose different communication schemes with different tradeoffs, or let the user implement one if the provided ones don't work for his use case

The second idea I advocate for is that a member function API would be better than the current free function implementation for the following reasons:
- No weakly-type `MPI_Comm` object leaks into the client code with this approach
- All MPI calls require a `MPI_Comm` object, so it makes sense to implement these as member functions IMO
- The choice of a communication mode is often not specific to a single MPI call. Therefore, although it is not demonstrated in the PR code, the `Communicator` abstraction could be used to store this kind a general default parameters and therefore provide a simpler syntax for most of MPI calls: `auto req = comm.irecv( view, from_rank, tag );` is more elegant and user-friendly than the more verbose `auto req = KokkosComm::irecv< RecvMode >( view, from_rank, tag, MPI_COMM_WORLD );`, especially when doing many communication calls IMO
- It also enables to decouple construction from behavior (e.g. I can create a communicator object with some choices of communication modes, and then hand this to my solver which does not have to care about these considerations which are encapsulated in the communicator object)

2024-05-10 22:12 UTC, dutkalex commented
> * The choice of a communication mode is often not specific to a single MPI call. Therefore, although it is not demonstrated in the PR code, the `Communicator` abstraction can be used to store this kind of general parameters.

I have made the necessary changes to illustrate the potential of the approach. Also tagging @cwpearson for reference

2024-05-10 23:16 UTC, devreal commented
> This PR proposes a first draft of a flexible enough design (IMO at least, please let me know if I'm missing something), which decouples the wrapping of the raw MPI functionalities from the higher-level communication scheme

Do you mean "decoupling communication and resource management"? We could have a way to allow users to query the requirements for a given view to manage resources explicitly, both for datatypes and temporary buffers:


```C
// query whether we need a temporary buffer or a derived datatype
std::variant<size_t, KokkosComm::Type> opt = KokkosComm::query(view);
if (std::holds_alternative<size_t>(opt)) {
  // provide a temporary buffer for packing, takes ownership until completion
  ensure_size(std::get<size_t>(opt), my_properly_sized_buf);
  KokkosComm::isend(view, comm, ..., my_properly_sized_buf);
} else {
  // provides a datatype we have cached (could be built-in for contiguous views)
  KokkosComm::isend(view, comm, ..., std::get<KokkosComm::Type>(opt));
}

// no cached information for another_view, let kokkos figure it out
KokkosComm::isend(another_view, comm, ...,);
```

2024-05-11 09:37 UTC, dutkalex commented
> Do you mean "decoupling communication and resource management"? 

Yes!

> We could have a way to allow users to query the requirements for a given view to manage resources explicitly, both for datatypes and temporary buffers

This seems reasonable to me, although I dont quite get where you get your buffer from in your example...

2024-05-11 14:11 UTC, dutkalex commented
@devreal considering your example, an interesting approach could be to have the `communicator.member_fcn()` API have the same semantics as the raw MPI call and be just syntactic sugar basically, and have the free functions implement the more elaborate semantics, as in the last line of your example:
```cpp
// no cached information for another_view, let kokkos figure it out
KokkosComm::isend(another_view, comm, ...,);
```

2024-05-13 07:34 UTC, dssgabriel commented
> - No weakly-type MPI_Comm object leaks into the client code with this approach

I like this approach. We had already considered adding a `Communicator` type that would wrap the underlying `MPI_Comm` and the Kokkos execution space for performance-related reasons. It would allow us to bypass some MPI assertions (e.g., checking pointer provenance in a GPU-only context is expensive and useless as Kokkos can already statically prove the view is in GPU memory).

> - With this approach, no KokkosComm:: prefix is needed which makes the syntax simpler
> - All MPI calls require a MPI_Comm object, so it makes sense to implement these as member functions IMO

I think this is indeed an elegant solution that reduces the verbosity of the code, and it's also the approach taken in other languages implementing MPI bindings (e.g., see [rsmpi](https://github.com/rsmpi/rsmpi)).

This effort needs a few more iterations, but we should consider it.

2024-05-14 17:29 UTC, cwpearson commented
+ some unit tests please!

2024-05-14 22:06 UTC, dutkalex commented
> some unit tests please!

Do you prefer to test by source file or by functionality?

2024-05-21 15:07 UTC, cwpearson requested changes

2024-05-21 15:07 UTC, cwpearson commented on src/impl/KokkosComm_mpi.hpp
I don't see a good reason to consolidate a bunch of things into a single header here. Let's split it up into

1. The special handling around #include <mpi.h>
2. KokkosComm_config.h (version-related stuff, a future home for other config things)
3. the `mpi_type` thing
4. The communicator class

2024-05-21 15:07 UTC, cwpearson commented on unit_tests/test_barrier.cpp
Two separate tests

2024-05-21 15:07 UTC, cwpearson commented on src/impl/KokkosComm_send.hpp
> -void send(const SendView &sv, int dest, int tag, MPI_Comm comm) {
Okay to have the proposed interface (again, should call below with `DefaultExecutionSpace()` as first argument, but keep this one as well as a very low-level wrapper.

2024-05-21 15:07 UTC, cwpearson commented on src/impl/KokkosComm_reduce.hpp
> +template <KokkosView SendView, KokkosView RecvView>
This should just call the below with `DefaultExecutionSpace()` as the first argument.

2024-05-21 15:08 UTC, cwpearson requested changes
And at least a skeleton of documentation, and if the documentation is incomplete, open one or more issues against yourself 😄

2024-05-23 09:13 UTC, dutkalex commented on src/impl/KokkosComm_mpi.hpp
What do you mean by the version-related stuff?

2024-05-23 09:30 UTC, dutkalex commented on src/impl/KokkosComm_mpi.hpp
> I don't see a good reason to consolidate a bunch of things into a single header here

The idea was to keep contained in a single place the raw `MPI_***` primitives, and have all the other file use the type-safe API

2024-05-23 09:53 UTC, dutkalex commented on src/impl/KokkosComm_send.hpp
> -void send(const SendView &sv, int dest, int tag, MPI_Comm comm) {
I was thinking about this the other way around and have the more complex APIs be implemented in terms of the low level ones

2024-05-23 09:56 UTC, dutkalex commented
> And at least a skeleton of documentation, and if the documentation is incomplete, open one or more issues against yourself 😄

Noted. Maybe I'll wait to be sure we are all on the same page before writing the doc though ;)

2024-09-09 18:54 UTC, closed without merging